### ISSUE TITLE
Is the api down?

### ISSUE THREAD

**Issue by zaklampert** [strawpoll/strawpoll#74]
i'm attempting to create a poll in node like so:
```
import rp from 'request-promise';
rp({
  uri: 'https://strawpoll.me/api/v2/polls',
  method: 'POST',
  headers:{
    'Content-Type':'application/json'
  },
  json: {
	"title":"favorite day of the week",
	"options":[
		"monday", "tuesday","wednesday","thursday","friday"
		],
		"multi":true
  }
}).then(res=>{
  console.log(res);
  process.exit();

})
.catch(err=>{
  console.log(err.message)
  process.exit();

})
```

And i'm getting an error `307 - undefined`

**Comment by megadrive** [comment]
I am currently still getting that. The response I get is this:

```
{ HTTPError
    at ee.on.stream.catch.then.data (d:\ozbt\node_modules\got\index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  message: 'Response code 307 (Temporary Redirect)',
  host: 'strawpoll.me',
  hostname: 'strawpoll.me',
  method: 'POST',
  path: '/api/v2/polls',
  statusCode: 307,
  statusMessage: 'Temporary Redirect' }
```

**Comment by bufutda** [comment]
You're getting a 307 because you're not sending the request to the right URI (Missing `www`)
```
import rp from 'request-promise';
rp({
  uri: 'https://www.strawpoll.me/api/v2/polls',
  method: 'POST',
  headers:{
    'Content-Type':'application/json'
  },
  json: {
	"title":"favorite day of the week",
	"options":[
		"monday", "tuesday","wednesday","thursday","friday"
		],
		"multi":true
  }
}).then(res=>{
  console.log(res);
  process.exit();

})
.catch(err=>{
  console.log(err.message)
  process.exit();

})
```

**Comment by advaith1** [comment]
It does work with www, however the [docs](https://github.com/strawpoll/strawpoll/wiki/API) does not say to use www. Could @dandirks or someone else fix it?
